// console.log(2>=1)
// console.log("2"==2)
// console.log("2"===2)
// console.log("2"!=2)
// console.log(2!="2")
// console.log("2" > 1)
// console.log(null > 0)
// console.log(null == 0)
// console.log(null >= 0)//
// console.log(undefined > 0)
// console.log(undefined == 0)
// console.log(undefined >= 0)
// console.log(undefined == null)
// console.log(undefined === null)
// console.log(null == null)
// console.log(null === null)
// console.log(NaN == NaN)
// console.log(NaN === NaN)
// console.log(NaN != NaN)
// console.log(NaN !== NaN)
// console.log(NaN > NaN)
// console.log(NaN < NaN)
// console.log(NaN >= NaN)
// console.log(NaN <= NaN)
console.log(NaN == undefined)
console.log(NaN == null)
console.log(NaN == 0)
console.log(NaN == false)
console.log(NaN == "")
console.log(NaN == "0")
console.log(NaN == "false")
console.log(NaN == "NaN")
console.log(NaN == "undefined")
console.log(NaN == "null")
console.log(NaN == "NaN")